/**
 * Generated by Dragonfly SDK.
 */
package com.buglabs.bug.module.base.tests;


import org.osgi.framework.BundleActivator;
import org.osgi.framework.BundleContext;
import org.osgi.util.tracker.ServiceTracker;

import com.buglabs.application.ServiceTrackerHelper;
import com.buglabs.bug.base.pub.IBUG20BaseControl;
import com.buglabs.bug.base.pub.ITimeProvider;


/**
 * BundleActivator for Com_buglabs_bug_module_camera_tests.  The OSGi entry point to the application.
 *
 */
public class Activator implements BundleActivator {
	 /**
	 * OSGi services the application depends on.
	 */
	private static final String [] services = {		
		IBUG20BaseControl.class.getName(),
		ITimeProvider.class.getName(),
	};
	private ServiceTracker serviceTracker;
	
	public void start(BundleContext context) throws Exception {
		//Begin tracking services, and when all services are available, create thread and call ManagedRunnable.run().
		serviceTracker = ServiceTrackerHelper.openServiceTracker(context, services, new TestMain());
		
	}

	public void stop(BundleContext context) throws Exception {
		
		//Will cause the ManagedRunnable.shutdown() to be called.
		serviceTracker.close();
	}
}